import Head from "next/head";
import { Inter } from "next/font/google";
import { Main } from "../components/Main";
import styles from "../styles/Home.module.css";
import { Header } from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  return (
    <div className={styles.content}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main page="about" />
    </div>
  );
}
